# Generated by Django 5.0.8 on 2024-08-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='meal',
            new_name='food_name',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='costumer',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='food',
            name='day_of_week',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Modnay'), ('Tue', 'Tuesday'), ('Wed', 'Wedensday'), ('Thur', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Sat', max_length=25),
        ),
        migrations.AddField(
            model_name='reservation',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservation',
            name='day_of_week',
            field=models.CharField(default='Sat', max_length=25),
        ),
    ]
