# Generated by Django 5.0.8 on 2024-08-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_meal_reservation_food_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
