# Generated by Django 5.0.8 on 2024-08-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_reservation_last_name_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='day_of_week',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='food',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='food',
            name='day',
            field=models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Modnay'), ('Tue', 'Tuesday'), ('Wed', 'Wedensday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], default='Sat', max_length=25),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
