# Generated by Django 5.0.8 on 2024-08-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_rename_day_of_week_reservation_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='day',
            new_name='day_of_week',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='day',
            new_name='day_of_week',
        ),
    ]
