# Generated by Django 5.0.8 on 2024-09-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_day_food_day_of_week_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
