# Generated by Django 5.0.8 on 2024-10-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_reservation_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
