# Generated by Django 5.0.8 on 2024-10-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_reservation_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
