# Generated by Django 5.0.8 on 2024-10-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_food_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='slug',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
