# Generated by Django 5.0.8 on 2024-10-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_card_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
    ]
