# Generated by Django 5.2 on 2025-08-15 07:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_card_total_price_remove_food_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
