# Generated by Django 5.2 on 2025-08-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_food_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'کارت', 'verbose_name_plural': 'کارت ها'},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
