# Generated by Django 5.2 on 2025-08-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_card_options_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='day_of_week',
            field=models.CharField(choices=[('Sun', 'یکشنبه'), ('Mon', 'دوشنبه'), ('Tue', 'سه شنبه'), ('Wed', 'چهارشنبه'), ('Thu', 'پنجشنبه'), ('Fri', 'جمعه'), ('Sat', 'شنبه')], default='Sat', max_length=3),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='day_of_week',
            field=models.CharField(choices=[('Sun', 'یکشنبه'), ('Mon', 'دوشنبه'), ('Tue', 'سه شنبه'), ('Wed', 'چهارشنبه'), ('Thu', 'پنجشنبه'), ('Fri', 'جمعه'), ('Sat', 'شنبه')], default='sat', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
