# Generated by Django 5.2 on 2025-08-15 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_food_day_of_week_alter_reservation_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
