# Generated by Django 5.2 on 2025-08-22 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0022_group_alter_groupfoodprice_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='FoodGroup',
        ),
        migrations.AlterField(
            model_name='groupfoodprice',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
