# Generated by Django 5.2 on 2025-08-22 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_rename_group_foodgroup_alter_groupfoodprice_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupfoodprice',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.foodgroup'),
        ),
    ]
